//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQL_API_04.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public string Membership { get; set; }
        public int GroupID { get; set; }
        public string Message { get; set; }
        public string Content { get; set; }
        public int Zip { get; set; }
        public System.DateTime TimePosted { get; set; }
    }
}
