//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQL_API_04.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RealSub01 : DbContext
    {
        public RealSub01()
            : base("name=RealSub01")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<defaultSubGroup> defaultSubGroups { get; set; }
        public virtual DbSet<subGroup> subGroups { get; set; }
        public virtual DbSet<subMembership> subMemberships { get; set; }
    }
}
